
import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

// Phrases that YouTube auto-generates for audio/video titles.
// These are not real content titles, so we strip them from display.
const YOUTUBE_AUTO_TITLE_PHRASES = [
  "what you're hearing from youtube",
  "provided to youtube by",
  "auto-generated by youtube",
];

/**
 * Removes YouTube auto-generated phrases from a video title.
 * Falls back to the original title if cleaning would leave it empty.
 */
export const cleanVideoTitle = (title: string | null | undefined): string => {
  if (!title) return "";
  let cleaned = title;
  for (const phrase of YOUTUBE_AUTO_TITLE_PHRASES) {
    const index = cleaned.toLowerCase().indexOf(phrase);
    if (index !== -1) {
      cleaned = cleaned.slice(0, index).trim();
    }
  }
  // Remove trailing separators/dashes left after phrase removal
  cleaned = cleaned.replace(/[-–—:|]\s*$/g, "").trim();
  return cleaned || title;
};
