
project_id = "euincktvsiuztsxcuqfd"

[api]
# Disable port because URL is provided explicitly
port = 0
# No URL needed for Edge Functions
hostname = "localhost"

[functions.channel-subscribe]
verify_jwt = true
