
project_id = "euincktvsiuztsxcuqfd"

[functions.fetch-youtube-channel]
verify_jwt = true

[functions.fetch-youtube-videos]
verify_jwt = true

[functions.check-admin-status]
verify_jwt = true

[functions.get-public-videos]
verify_jwt = false

[functions.get-public-channel]
verify_jwt = false

[functions.fetch-channel-details]
verify_jwt = false

[functions.increment_counter]
verify_jwt = false
