
project_id = "euincktvsiuztsxcuqfd"

[functions.fetch-youtube-channel]
verify_jwt = true

[functions.fetch-youtube-videos]
verify_jwt = false

[functions.update-channel-thumbnails]
verify_jwt = false
